/**
 * Represents a command to be executed against an aggregate.
 * Commands express intent to change the system state.
 * 
 * @example
 * ```typescript
 * const command: Command = {
 *   commandId: 'cmd-123',
 *   commandType: 'PlaceOrder',
 *   aggregateId: 'order-456',
 *   timestamp: '2025-01-01T00:00:00.000Z',
 *   payload: { items: [{ sku: 'SKU-001', quantity: 2 }] },
 *   metadata: {
 *     userId: 'user-789',
 *     correlationId: 'corr-012',
 *   },
 * };
 * ```
 */
export interface Command {
  /** Unique identifier for this command (UUID recommended) */
  commandId: string;
  
  /** Type of the command (e.g., 'PlaceOrder', 'CancelOrder') */
  commandType: string;
  
  /** ID of the aggregate this command targets */
  aggregateId: string;
  
  /** ISO 8601 UTC timestamp when the command was issued */
  timestamp: string;
  
  /** Command-specific data payload */
  payload: Record<string, unknown>;
  
  /** Metadata for tracing and authorization */
  metadata: CommandMetadata;
}

/**
 * Metadata attached to every command for tracing and authorization.
 */
export interface CommandMetadata {
  /** ID of the user issuing the command */
  userId: string;
  
  /** ID to correlate related commands and events */
  correlationId: string;
  
  /** ID of the parent command (for command chains) */
  causationId?: string;
}

/**
 * Result of executing a command.
 * Contains success/failure status and resulting event IDs.
 * 
 * @example
 * ```typescript
 * // Success result
 * const success: CommandResult = {
 *   success: true,
 *   aggregateId: 'order-456',
 *   version: 5,
 *   eventIds: ['evt-001', 'evt-002'],
 * };
 * 
 * // Failure result
 * const failure: CommandResult = {
 *   success: false,
 *   aggregateId: 'order-456',
 *   version: 0,
 *   eventIds: [],
 *   error: 'Insufficient inventory',
 * };
 * ```
 */
export interface CommandResult {
  /** Whether the command executed successfully */
  success: boolean;
  
  /** ID of the aggregate that was modified */
  aggregateId: string;
  
  /** New version of the aggregate after command execution */
  version: number;
  
  /** IDs of events generated by this command */
  eventIds: string[];
  
  /** Error message if command failed */
  error?: string;
}
